services:
  - type: web
    name: kbmi-taller-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt && cd backend && PYTHONPATH=. python update_schema.py
    startCommand: cd backend && PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PROJECT_NAME
        value: "Kbmi Taller API"
      - key: PORT
        value: "10000"

  - type: web
    name: kbmi-taller-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: kbmi-taller-backend
          property: host
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          type: web
          name: kbmi-taller-frontend
          property: host
